Add installed version to status field of apicurio crd
integr8ly/apicurio-operator pull request #9
Opened 2018-12-12 15:17 UTC by JameelB

## What
Add the version of the Apicurio installed within the `status` field of the Apicurio CRD.

## Why
Ensure that the version of the product installed by the Apicurio operator is reflected in the `status.version` field.

## Verification Steps
1. Run `make cluster/prepare`
2. Run the operator locally.
3. Create the Apicurio custom resource
4. Ensure that the correct version is shown within the `status` field of the Apicurio custom resource

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

2018-12-12 15:32 UTC, odra commented
:eye:

2018-12-12 15:46 UTC, odra approved these changes

2018-12-12 16:36 UTC, maleck13 commented on pkg/apis/integreatly/v1alpha1/apicuriodeployment_types.go
> +	Version         string    `json:"version"`
I think we should remove version from here. The operator should decide the version not the user

2018-12-12 16:36 UTC, maleck13 requested changes
see comment above

2018-12-13 10:33 UTC, JameelB commented
@odra @maleck13 Closing this PR as this will be replaced by Apicurito in the new version of Fuse.

2018-12-13 10:33 UTC, closed without merging